apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  # tell skaffold to overwrite previously built images (should save disk space)
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/uscities-redis
      context: ../redis
      docker:
        dockerfile: Dockerfile.dev
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/uscities-mongodb
      context: ../mongodb
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - ../k8s/dev/*.yml